### ISSUE TITLE
esc2text unexpected output

### ISSUE THREAD

**Issue by nsatech** [receipt-print-hq/escpos-tools#38]
When I run esc2text on my binary file, I get the following output:

WARNING: Unknown command FS
PuTTYWARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC W
WARNING: Unknown command ESC FF
WARNING: Unknown command ESC S
WARNING: Unknown command GS FF
=~d@▒▒▒▒▒▒▒h▒ ▒▒:0▒UPh▒p`▒▒`▒x`▒▒`▒x`▒`9x`\▒`vxh▒p▒▒0▒▒0▒▒0▒▒0▒0▒)0▒@(▒L0▒g(x▒HQ`ey0p▒`▒▒HhhxHp6`xQP▒k▒x▒H▒▒▒`▒x▒7▒@

----

When I look at the binary, I can see alot of actual ESC/POS commands but in between it raster graphics. Is there something I am doing wrong to extract the text from this?

Thanks.

**Comment by mike42** [comment]
Usage is correct. Are you able to share your make/model of printer and a binary sample file so that I can inspect it and try to replicate?
