### ISSUE TITLE
NC / Python binary forwarder | dumper

### ISSUE THREAD

**Issue by mahmoudaljan** [receipt-print-hq/escpos-tools#48]
Hello,

Can you please help with a snipet of code that would dump and forward individual binary data bursts to a seperate file ?

**Comment by mike42** [comment]
Hi,

All of these tools work only on files. Since it's your setup, I would appreciate it if you did your own research on how to capture raw print jobs, and limited questions on the issue tracker to things which would help us to improve the command-line tools.
