### ISSUE TITLE
Printing images

### ISSUE THREAD

**Issue by dremoussenard** [receipt-print-hq/escpos-tools#52]
Hello,
We have a TM20II, connected to a debian server with USB.
We have some freeze event when printing images (gray level).
We change some image properties : resolution, size, etc
but sometimes, the printing freeze.
And when the image printing ik ok, we can see some blank lines.
Is there any buffer effects? Some characters/codes wich can freeze the printer?
We tried some 300 pixels width at 72 dpi (arround 200 pixels height). It seems that the problem is not so frequent. With some 500 pixels width images, it 1 freeze over 3 images.
Thank you for your help.
Didier

**Comment by dremoussenard** [comment]
![example](https://user-images.githubusercontent.com/1711028/45535273-35622200-b7fe-11e8-9097-be0f1bef3dda.jpg)

**Comment by mike42** [comment]
This project contains command-line tools for reading ESC/POS binary files to get some useful information out of them as text, HTML, or image files.

I don't think your issue has anything to do with these tools, so I'm closing this as off-topic.
