### ISSUE TITLE
Print Margin on Top

### ISSUE THREAD

**Issue by hasnainkhawaja** [receipt-print-hq/escpos-tools#57]
I am getting margin on top. Printer model RP-76II Rongta  any idea how to solve this?

**Comment by hasnainkhawaja** [comment]
![8176c0ba-a068-45cc-b992-36a182c8f619](https://user-images.githubusercontent.com/17934259/50550669-89522300-0c96-11e9-8291-1cccc03c0c95.jpg)

**Comment by mike42** [comment]
Closing this as off-topic, this is not a printer help forum.

This project contains command-line tools for reading ESC/POS binary files to get some useful information out of them as text, HTML, or image files.
