### ISSUE TITLE
How to gerate Invoice like this? Or how to add html in print view?

### ISSUE THREAD

**Issue by Luqman000** [receipt-print-hq/escpos-tools#60]
any one help me for gerating a invoice as in attachment.  Specaily Product Description Section
[https://images.app.goo.gl/nHAwk2nhLSZXmAbf6](url)

**Comment by mike42** [comment]
There is no mention of this software in your poise, so I'm currently assuming that this is unrelated to this project.

If this is incorrect, then please explain what you are doing, how `escpos-tools` is involved, and which issue you have encountered.

**Comment by Luqman000** [comment]
Hello,
Hope You are well,
My question is how to add HTML in escope-tool. Mean how to allign item in
same line. Issue for me in attached file
please check it
