### ISSUE TITLE
fopen(/tmp/test.bin): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by lebroncho** [receipt-print-hq/escpos-tools#65]
I've been trying to test in escpos using Laravel framework. 

```
use Mike42\Escpos\PrintConnectors\FilePrintConnector;
use Mike42\Escpos\PrintConnectors\WindowsPrintConnector;
use Mike42\Escpos\Printer;

public function store()
{
    $connector = new FilePrintConnector("/tmp/test.bin"); //this code
    $printer = new Printer($connector);
    $printer -> cut();
    $printer -> close(); 
}        
```
It produced an error `fopen(/tmp/test.bin): failed to open stream: No such file or directory`. I don't have any idea on how to fix this if it is in laravel or in escpos.

**Comment by mike42** [comment]
Just guessing, but `/tmp` does not exist on Windows.

In any case, you're in the wrong repo: `escpos-php` writes ESC/POS, `escpos-tools` reads it.
